---
- import_tasks: setup.yml

- name: "Configure default mountpoint directory"
  file:
    path: "{{ appuio_openshift_localstorage_mountpoint_parent }}"
    state: directory
    owner: root
    group: root
    mode: 0755
    seuser: unconfined_u
    serole: object_r
    setype: default_t
    selevel: s0

- set_fact:
    l_node: "{{ inventory_hostname.split('.')[0] }}"

- set_fact:
    l_luks_key: "{{ lookup('env', 'ANSIBLE_OPENSHIFT_LOCALSTORAGE_LUKS_KEY_' ~ l_node) | default('', True) }}"

- when: l_luks_key != ""
  block:
    - name: "Create tempfile for LUKS key"
      tempfile:
        state: file
        suffix: .key
      register: r_keyfile

    - name: "Store LUKS key in tempfile"
      copy:
        dest: "{{ r_keyfile.path }}"
        content: "{{ l_luks_key|trim }}"

- include_tasks: volume.yml
  with_dict: '{{ appuio_openshift_localstorage }}'

- name: "Remove tempfile containing LUKS key"
  file:
    path: "{{ r_keyfile.path }}"
    state: "absent"
  when: r_keyfile.path is defined
