---
- import_tasks: setup.yml

- name: "Configure default mountpoint directory"
  file:
    path: "{{ appuio_openshift_localstorage_mountpoint_parent }}"
    state: directory
    owner: root
    group: root
    mode: 0755
    seuser: unconfined_u
    serole: object_r
    setype: default_t
    selevel: s0

- include_tasks: volume.yml
  with_dict: '{{ appuio_openshift_localstorage }}'
  tags:
    - always
